---
- hosts: all
## This playbook installs the dependencies for the *nix OCS Inventory NG Agent
## Then it grabs the agent install archive and OCS server cert and installs them
  - name: Get variables from *_vars directories and subdirectories
    include_vars:
      dir: "{{ item }}"
      with_items:
        - group_vars
        - host_vars

  tasks:
#updates the apt cache if the current cache is older than 1 week
    - name: Apt cache update on Debian systems
      apt: update_cache=yes cache_valid_time=600
      when: ansible_architecture == "x86_64" and ansible_os_family == "Debian"
      changed_when: false



    - name: Install needed apt files on Debian systems
      apt: name="{{ item }}" state=latest
      with_items:
        - nmap
        - gcc
        - build-essential
        - cpanminus
        - ipmitool
        - dmidecode
        - read-edid
        - openssl
        - cups
        - cups-client
        - libperl-dev
        - libssl-dev
        - libcups2-dev
        - libcupsfilters-dev
        - libcupsimage2-dev
        - libcupsimage2
      when: ansible_architecture == "x86_64" and ansible_os_family == "Debian"


  #installs these packages using yum when run on a CentOS or RHEL host
    - name: Install required packages on CentOS/RHEL
      yum: name="{{ item }}" state=present
      with_items:
        - perl-CPAN
        - nmap
        - gcc
        - make
        - autoconf
        - perl-App-cpanminus
        - ipmitool
        - dmidecode
        - perl-Parse-EDID
        - openssl
        - cups
        - cups-client
        - perl-devel
        - openssl-devel
        - cups-devel
        - cups-filters-devel
        - cups-filters-libs
        - cups-filters
        - cups-libs
        - cups-lpd
        - t1lib
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

  #installs PHP modules with pear
    - name: Install Perl modules
      cpanm: name="{{ item }}" system_lib=yes
      with_items:
        - SUPER
        - Net::SSLeay
        - Proc::Daemon
        - Proc::PID::File
        - Digest::MD5
        - XML::Simple
        - Net::IP
        - LWP
        - LWP::Protocol::https
        - Net::CUPS
        - Net::SNMP
        - Net::Netmask
        - Nmap::Parser
        - File::Temp
        - Data::UUID
        - Parse::EDID
        - Compress::Zlib
        - Archive::Zip
        - HTML::Parser
        - Crypt::SSLeay
        - URI
        - Test::Builder::Module
        - XML::NamespaceSupport
        - HTML::Tagset
        - Module::ScanDeps
        - PAR::Packer
        - AutoLoader
        - PAR
        - PAR::Dist
        - Test::Requires
        - Test::MockModule
        - File::Remove
        - YAML::Tiny
        - Getopt::ArgvFile
        - ExtUtils::Install
        - ExtUtils::ParseXS
        - XML::SAX
        - Test::More

    - name: Extract agent files
      unarchive:
        src: "{{ ocs_unix_agent_archive }}"
        dest: /root/
        remote_src: yes
        validate_certs: no

    - name: Move SSL files
      get_url: url="{{ ssl_url }}/{{ item }} dest=/etc/ssl/certs/ owner=root group=root validate_certs=no"
      with_items:
        - ocs-cert.crt
        - ca-cert.crt

    - name: Configure and launch ocs inventory agent
      shell: cd /root/Ocsinventory-Unix-Agent-2.3 && env PERL_AUTOINSTALL=1 perl Makefile.PL && make && make install && perl postinst.pl --nowizard --server=https://ocs.internal.fbgncenter.org/ocsinventory --crontab --tag=server --download
